name: CI / CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-2'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Logseq Publish
  #       uses: pengx17/logseq-publish@0.1.5
  #       with:
  #         dest: www

  #     - name: Add .nojekyll file
  #       run: touch www/.nojekyll

  #     - name: Deploy to gh-pages
  #       uses: JamesIves/github-pages-deploy-action@4.1.9
  #       with:
  #         branch: gh-pages
  #         folder: www
  #         clean: true
  #         clean-exclude: |
  #           CNAME
  #           .nojekyll  

  build2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: inject script
          run: ls
        # run:  sed -i '' 's+<head>+<head>\n    <script async src="https://www.googletagmanager.com/gtag/js?id=G-CLE18BXBH6"></script>\n    <script>\n        window.dataLayer = window.dataLayer || [];\n        function gtag(){dataLayer.push(arguments);}\n        gtag('js', new Date());\n          gtag('config', 'G-CLE18BXBH6');\n    </script>\n    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1685973888441817" crossorigin="anonymous">\n    </script>+g' ./index.html
      # - name: "S3"
      #   run: aws s3 sync ./ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --acl public-read --delete --cache-control max-age=604800
      # - name: "Create AWS Cloudfront Invalidation"
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"